### ISSUE TITLE
Gcode File Flipped

### ISSUE THREAD

**Issue by bfaught** [Scott-Cooper/Drawbot_image_to_gcode_v2#4]
Thank you so much for sharing this amazing program! I am having an issue with the generated Gcode file. the test images all show up normal but the gcode file is flipped and the orgin is being created at the top of the image. Any help would be greatly appreciated. Thanks again!
![screenshot 3](https://user-images.githubusercontent.com/25714335/31636912-036f0398-b292-11e7-9bff-5566a290deff.png)

**Comment by bfaught** [comment]
I now see that the code was originally created for a polargraph style drawing machine. I am new to coding and cannot make sense of the rotation feature, any chance you could show me how to get it rotated 180?

**Comment by Scott-Cooper** [comment]
Thanks for the comments bfaught.  This has got me befuddled, but I have a few thoughts.

The "r" key binding only rotates the image for display purposes, and does not change the gcode.

The auto center-crop can also be avoided by commenting out image_crop(); in the pre_processing() function.  You also probably want to comment out image_rotate(); in the setup_squiggles function.  These are both cheap fixes to solve for physical limits of my particular machine.

You are correct about the weird coordinate system used by my code.  It was developed with only a drawbot/polargraph in mind.  The coordinate system used can be described here (https://docs.google.com/drawings/d/1RyHrsHJsZNmhhTTr34jDhYRZ16E500V7iOMiLZUEsnk/edit)

This still does not explain the results you got.  I assume you set paper_top_to_origin = 0.  The picture below is what I would have expected.  Sorry I don't have an answer for you.  I'll keep working on it.
![bfaught_coordinates](https://user-images.githubusercontent.com/1677098/31758886-e19e14fe-b474-11e7-9aa4-ce01891f6137.jpg)

**Comment by bfaught** [comment]
I was able to fix it using some workarounds, I really appreciate you sharing this I am blown away. I have been working on plans for a wall mounted cartesian style plotter that I have just finished using v slot rail. Its almost all 3D printed parts and a inexpensive build. I would be happy to send you the plans if you would like.

**Comment by vovboc** [comment]
I ran into a similar problem, how can it be solved?

**Comment by vovboc** [comment]
![flip_img](https://user-images.githubusercontent.com/34169953/35238487-9d792ce2-ffbe-11e7-9b37-41bdd147bc82.jpg)
![test_dr_b](https://user-images.githubusercontent.com/34169953/35238488-9d955f84-ffbe-11e7-979b-bf6528ea210d.jpg)

**Comment by vovboc** [comment]
I change "Y" to "Y-" and "Y-" to "Y" in the finished G-code
Everything is done in a text editor in 5 minutes.
