### ISSUE TITLE
The question of the beginner

### ISSUE THREAD

**Issue by vovboc** [Scott-Cooper/Drawbot_image_to_gcode_v2#5]
How does it start in Processing? In what directory, what files should be placed?
All ok..... 
Fantastically beautiful work! While I can not open the created files.
SVG 6Mb, but inkscape freezes. I will read and try. Thank you for the great and useful work.

**Comment by vovboc** [comment]
The problem is to open SVG. What to watch? What am I doing wrong?
![2017-12-03 12 52 12](https://user-images.githubusercontent.com/34169953/33524240-a92d9800-d829-11e7-9702-dda7119a8e86.png)

**Comment by Scott-Cooper** [comment]
This should finally be fixed with the latest [commit](https://github.com/Scott-Cooper/Drawbot_image_to_gcode_v2/commit/a6339b3f1348de656c0e866cfe2e9a3ed121a58c)  Thanks again vovboc for helping me debug this.
