### ISSUE TITLE
Processing decimal separator question

### ISSUE THREAD

**Issue by gpeter62** [Scott-Cooper/Drawbot_image_to_gcode_v2#6]
Hi Scott!
I enjoy your fantastic code with my Polargraph machine. :)
This is the best conversion from jpeg to gcode, I have ever used!!!

My question is:
Do you know, how can I change the default decimal separator character in Processing 3?
My local character is "," instead of "." and it is a problem in GCODE.

Other question:
What is your suggestion, if I want to use 0.8mm pen? Which parameters should be changed?
Thx: Peter

**Comment by Scott-Cooper** [comment]
I just finished uploading a new version that can override the locale decimal separator for the gcode files.
Look in the file "Drawbot_image_to_gcode_v2.pde" for "gcode_decimal_seperator" (currently line 29). 

The pen width thing is something I really have not worked out in my brain yet.  I usually set my image_size_x to 711mm and my image_scale() to 1000px.   This ratio 0.711mm is about the width of my copix markers.    So if take your image_size_x / 0.8, I think this is about what you want to set your image_scale to.  If you get too much white space between your lines, and black areas are not covering completely, just increase your image_scale.

Hope that helps, and thanks for the kind words.
Scott,

**Comment by gpeter62** [comment]
I am grateful for your help, I tried the update, it works fine. Thank you!
Happy New Year!
Peter

This is one of my first pictures (MrWhite from Breaking Bad):
![img_20171229_130459](https://user-images.githubusercontent.com/34945081/34462552-a757eb88-ee46-11e7-9b30-6dffd08b426a.jpg)
